### ISSUE TITLE
Not displaying porgress

### ISSUE THREAD

**Issue by cyber-hunt7** [KevCui/soaper-dl#28]
Does anyone know how i can use this script to display the progress of downloading a episode. It only show when a subtitle is downloading but not when a video is downloading.

**Comment by KevCui** [comment]
Hey @cyber-hunt7, there is no progress for video downloading. One way I can think of it to check file size during download. I know, it's not convenient, but I cannot find an easy way to implement progress bar so far. Sorry.

**Comment by cyber-hunt7** [comment]
Can’t you use your old script from soap2day-dl that one was working perfectly.

**Comment by KevCui** [comment]
Hey @cyber-hunt7, soap2day is gone, old script won't work. soaper doesn't provide mp4 file to download, only m3u8 list. So, new script is not possible to behave 100% like old script.

**Comment by cyber-hunt7** [comment]
Ah ok cool thank you
